# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
---
jobs:
  build:
    docker:
    -
      image: "circleci/android:api-28"
    environment:
      JVM_OPTS: "-Xmx3200m"
    steps:
    - checkout
    -
      restore_cache:
        key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"app/build.gradle\" }}"
    -
      run:
        command: "sudo chmod +x ./gradlew"
        name: "Chmod permissions"
    -
      run:
        command: "./gradlew androidDependencies"
        name: "Download Dependencies"
    -
      save_cache:
        key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"app/build.gradle\" }}"
        paths:
        - ~/.gradle
    -
      run:
        TERM: dumb
        command: "android list target"
        environment: ~
        name: "Lists installed targets"
    -
      run:
        command: "sdkmanager --list --verbose | grep system-images"
        name: "Show list of system-images"
    -
      run:
        command: "./gradlew test"
        name: "Run UnitTest"
    -
      store_artifacts:
        destination: reports
        path: app/build/reports
    -
      store_test_results:
        path: app/build/test-results
    working_directory: ~/code
version: 2